# Generated by Django 6.0.3 on 2026-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_mainbannercard_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainbannercard",
            name="bg_color",
            field=models.CharField(blank=True, default="#315efb", max_length=20),
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
