# Generated by Django 6.0.3 on 2026-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_mainbannercard_bg_color_mainbannercard_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("paper", "지류"), ("mobile", "모바일")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("buy_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sell_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sort", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
