# Generated by Django 6.0.3 on 2026-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_giftprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftcardPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PAPER", "지류(종이)"), ("MOBILE", "모바일")],
                        default="PAPER",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "buy_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sell_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sort", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["kind", "sort", "id"],
            },
        ),
    ]
