# Generated by Django 6.0.3 on 2026-03-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_mainad"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="companies/"),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("link_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
