# Generated by Django 6.0.3 on 2026-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_lead_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredcompany",
            name="agency_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="등록기관"),
        ),
        migrations.AddField(
            model_name="registeredcompany",
            name="biz_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="사업자등록번호"
            ),
        ),
        migrations.AddField(
            model_name="registeredcompany",
            name="detail_content",
            field=models.TextField(blank=True, verbose_name="상세설명"),
        ),
        migrations.AddField(
            model_name="registeredcompany",
            name="office_address",
            field=models.CharField(blank=True, max_length=200, verbose_name="영업소"),
        ),
        migrations.AddField(
            model_name="registeredcompany",
            name="reg_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="등록번호"),
        ),
        migrations.AddField(
            model_name="registeredcompany",
            name="warning_text",
            field=models.TextField(blank=True, verbose_name="주의사항"),
        ),
    ]
