# Generated by Django 6.0.3 on 2026-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_inquiry_recentview_favoritecompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardpost",
            name="category",
            field=models.CharField(
                choices=[("department", "백화점"), ("gift", "상품권"), ("etc", "기타")],
                default="etc",
                max_length=20,
            ),
        ),
    ]
