# Generated by Django 6.0.3 on 2026-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0012_alter_boardpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="board/"),
        ),
        migrations.AlterField(
            model_name="boardpost",
            name="board_type",
            field=models.CharField(
                choices=[
                    ("BUY", "구매게시판"),
                    ("SELL", "판매게시판"),
                    ("FREE", "자유게시판"),
                ],
                max_length=20,
            ),
        ),
    ]
