# Generated by Django 6.0.3 on 2026-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_boardcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
