# Generated by Django 6.0.3 on 2026-04-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0015_signupverification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignupVerification",
        ),
        migrations.AlterModelOptions(
            name="giftcardprice",
            options={},
        ),
        migrations.AddField(
            model_name="giftcardprice",
            name="buy_price",
            field=models.PositiveIntegerField(default=0, verbose_name="매입가"),
        ),
        migrations.AddField(
            model_name="giftcardprice",
            name="face_value",
            field=models.PositiveIntegerField(default=0, verbose_name="액면가"),
        ),
        migrations.AddField(
            model_name="giftcardprice",
            name="sell_price",
            field=models.PositiveIntegerField(default=0, verbose_name="판매가"),
        ),
        migrations.AlterField(
            model_name="giftcardprice",
            name="buy_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="매입 퍼센트"
            ),
        ),
        migrations.AlterField(
            model_name="giftcardprice",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="노출 여부"),
        ),
        migrations.AlterField(
            model_name="giftcardprice",
            name="kind",
            field=models.CharField(
                choices=[("PAPER", "지류(종이)"), ("MOBILE", "모바일")],
                max_length=10,
                verbose_name="구분",
            ),
        ),
        migrations.AlterField(
            model_name="giftcardprice",
            name="name",
            field=models.CharField(max_length=50, verbose_name="상품권명"),
        ),
        migrations.AlterField(
            model_name="giftcardprice",
            name="sell_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="판매 퍼센트"
            ),
        ),
        migrations.AlterField(
            model_name="giftcardprice",
            name="sort",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="정렬순서"),
        ),
    ]
