# Generated by Django 6.0.3 on 2026-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_delete_signupverification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredcompany",
            name="ecommerce_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="통신판매업 신고번호"
            ),
        ),
    ]
