# Generated by Django 6.0.3 on 2026-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0017_registeredcompany_ecommerce_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpost",
            name="giftcard_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="boardpost",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
