# Generated by Django 6.0.3 on 2026-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0018_boardpost_giftcard_type_boardpost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpost",
            name="available_date",
            field=models.DateField(blank=True, null=True, verbose_name="거래 가능일"),
        ),
        migrations.AddField(
            model_name="boardpost",
            name="face_value",
            field=models.IntegerField(default=0, verbose_name="상품권 금액"),
        ),
        migrations.AlterField(
            model_name="boardpost",
            name="board_type",
            field=models.CharField(
                choices=[("BUY", "구매게시판"), ("SELL", "판매게시판")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="boardpost",
            name="giftcard_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="상품권 종류"
            ),
        ),
        migrations.AlterField(
            model_name="boardpost",
            name="price",
            field=models.IntegerField(default=0, verbose_name="희망가격"),
        ),
    ]
