# Generated by Django 6.0.3 on 2026-04-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0019_boardpost_available_date_boardpost_face_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainbannercard",
            name="bg_color",
        ),
        migrations.RemoveField(
            model_name="mainbannercard",
            name="image",
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="agency",
            field=models.CharField(blank=True, max_length=100, verbose_name="등록기관"),
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="business_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="사업자등록번호"
            ),
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="ecommerce_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="통신판매업 신고번호"
            ),
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="extra_desc",
            field=models.TextField(blank=True, verbose_name="부가설명"),
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="office_address",
            field=models.CharField(blank=True, max_length=200, verbose_name="영업소"),
        ),
        migrations.AddField(
            model_name="mainbannercard",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="연락처"),
        ),
        migrations.AlterField(
            model_name="mainbannercard",
            name="desc",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="mainbannercard",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="노출 여부"),
        ),
        migrations.AlterField(
            model_name="mainbannercard",
            name="link_url",
            field=models.URLField(blank=True, verbose_name="바로가기 링크"),
        ),
        migrations.AlterField(
            model_name="mainbannercard",
            name="sort",
            field=models.IntegerField(default=1, verbose_name="정렬 순서"),
        ),
        migrations.AlterField(
            model_name="mainbannercard",
            name="title",
            field=models.CharField(max_length=100, verbose_name="업체명"),
        ),
    ]
