# Generated by Django 6.0.3 on 2026-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0021_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
